version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: [ "sh", "/usr/src/app/entrypoint.sh" ]
    volumes:
      - "./backend:/usr/src/app"
    ports:
      - ${BACKEND_PORT}:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://${HOST}:${BACKEND_PORT}
    volumes:
      - "./frontend:/usr/src/app"
    ports:
      - ${FRONTEND_PORT}:3000
    depends_on:
      - backend
