version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tic_tac_toe_game
    env_file:
      - .env
    entrypoint: [ "sh", "/usr/src/app/entrypoint.sh" ]
    command: gunicorn 'manage:app' --log-level=debug --worker-class eventlet --workers 1 --bind 0.0.0.0:5000 --reload
    volumes:
      - "./backend:/usr/src/app"
    ports:
      - ${BACKEND_PORT}:5000
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://${HOST}:${BACKEND_PORT}
    volumes:
      - "./frontend:/usr/src/app"
    ports:
      - ${FRONTEND_PORT}:3000
    depends_on:
      - backend
